# The objective here is to enrich with clinical data all platekeys/participantIDs we do have selected for the research cohort study
date ()
Sys.info ()[c("nodename", "user")]
commandArgs ()
rm (list = ls ())
R.version.string ## "R version 3.3.2 (2016-10-31)"

# libraries
library(dplyr)

# setwd
setwd("~/CGR/kibanez/STRs/GEL_STR/summer_2019/research_cohort/")

# Clinical data retrieved from RE on september 2019
clinical_data = read.csv("../clinical_data/rd_genomes_all_data_250919.tsv",
                         header = TRUE,
                         stringsAsFactors = FALSE,
                         sep = "\t")
dim(clinical_data)
# 1056568  26

# List of all VCF files we have generated by running EH
l_vcf = read.table("./list_vcf_research_cohort.tsv", stringsAsFactors = F)
l_vcf = l_vcf$V1
length(l_vcf)
# 86457


# Separate in GRCh37 and GRCh38
clinical_data_b37 = clinical_data %>% filter(genome_build %in% "GRCh37")
dim(clinical_data_b37)
# 136800  26

clinical_data_b38 = clinical_data %>% filter(genome_build %in% "GRCh38")
dim(clinical_data_b38)
# 877169  26


clinical_data_na = clinical_data %>% filter(is.na(genome_build))
dim(clinical_data_na)
# 35898 26

# Create a table with clinical data 
#LP_number Gel_ID	Family_ID	Relationship 	Affection status	Gender	YearOfBirth	Disease	Disease_subgroup	Disease_group

research_b37 = clinical_data_b37 %>% 
  select(plate_key.x, participant_id, rare_diseases_family_id, biological_relationship_to_proband, affection_status, participant_phenotypic_sex, year_of_birth, normalised_specific_disease, disease_sub_group, disease_group, panel_name)
dim(research_b37)
# 136800  11

research_b37  = research_b37 %>% 
  filter(plate_key.x %in% l_vcf)
dim(research_b37)
# 113037  11


research_b38 = clinical_data_b38 %>% 
  select(plate_key.x, participant_id, rare_diseases_family_id, biological_relationship_to_proband, affection_status, participant_phenotypic_sex, year_of_birth, normalised_specific_disease, disease_sub_group, disease_group, panel_name)
dim(research_b38)
# 877169  11

research_b38 = research_b38 %>%
  filter(plate_key.x %in% l_vcf)
dim(research_b38)
#  766399  11


research_na = clinical_data_na %>%
  select(plate_key.x, participant_id, rare_diseases_family_id, biological_relationship_to_proband, affection_status, participant_phenotypic_sex, year_of_birth, normalised_specific_disease, disease_sub_group, disease_group, panel_name)
dim(research_na)
# 35898  11

# Check whether ALL VCF files in l_vcf have been included and enriched in both `research_b37` and `research_b38` tables
check_vcf_b37 = research_b37 %>% select(plate_key.x) %>% unique() %>% pull()
check_vcf_b38 = research_b38 %>% select(plate_key.x) %>% unique() %>% pull()
check_vcf_na = research_na %>% select(plate_key.x) %>% unique() %>% pull()

check_vcf = c(check_vcf_b37,
              check_vcf_b38,
              check_vcf_na)
length(check_vcf)
# 103438

# Which are not enriched?? Cancer samples?? <-- yes they are, we should enrich them as type (RD or Cancer)
setdiff(l_vcf, check_vcf)

length(setdiff(l_vcf, check_vcf))
# 380

## OUTPUT FILE
# When writing the output file that will facilitate us the statistical outcome when assessing the importance of our study, we will print the following:
# LP_number	Gel_ID	Family_ID	Relationship 	Affection status	Gender	YearOfBirth	Disease	Disease_subgroup	Disease_group
# Since there are many as NA's, because they are cancer, we will finally put everything on the same table

# First let's put all panel names as a list separated by ','

to_write = clinical_data %>%
  select(plate_key.x, participant_id, programme, genome_build, programme_consent_status, rare_diseases_family_id, biological_relationship_to_proband, affection_status, participant_phenotypic_sex, year_of_birth, normalised_specific_disease, disease_sub_group, disease_group, panel_name, family_group_type, family_medical_review_qc_state_code)
dim(to_write)
# 1056568  16

# Change all `NA` in `biological_relationship_to_proband` to "proband"
l_proband = which(to_write$biological_relationship_to_proband == "N/A")
to_write$biological_relationship_to_proband[l_proband] = "Proband"

list_panels = to_write %>% group_by(participant_id) %>% summarise(panel_list = toString(panel_name)) %>% ungroup() %>% as.data.frame()
dim(list_panels)
# 89163  2

# Remove `panel_name` from to_write
to_write = to_write[,-14]
dim(to_write)
# 1056568  15

to_write = left_join(to_write,
                     list_panels,
                     by = "participant_id")

to_write = unique(to_write)

to_write %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 113696

write.table(to_write, 
            file = "clinical_data_research_cohort_113696_genomes_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

# Since the whole table is super big, let's separate it
to_write_b38 = to_write %>%
  filter(genome_build %in% "GRCh38")
dim(to_write_b38)
# 69943  16

to_write_b37_na = to_write %>%
  filter(!genome_build %in% "GRCh38")
dim(to_write_b37_na)
# 47290  16


write.table(to_write_b38, 
            file = "clinical_data_research_cohort_113696_genomes_GRCh38_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

write.table(to_write_b37_na, 
            file = "clinical_data_research_cohort_113696_genomes_GRCh37_NA_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)


# Let's write the same info but removing the list of panels
write.table(to_write[,-16], 
            file = "clinical_data_research_cohort_113696_genomes_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

write.table(to_write_b38[,-16], 
            file = "clinical_data_research_cohort_113696_genomes_GRCh38_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

write.table(to_write_b37_na[,-16], 
            file = "clinical_data_research_cohort_113696_genomes_GRCh37_NA_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)



## ONLY OUTPUT FILES considering 86,457 genomes we have analysed through EHv2.5.5 and EHv3.0.0
clinical_data_research_genomes = to_write %>% filter(plate_key.x %in% l_vcf)
dim(clinical_data_research_genomes)
# 89090  16

clinical_data_research_genomes %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 86242

# Let's annotate the ones not included there with '.'
l_not_included = setdiff(l_vcf, clinical_data_research_genomes %>% select(plate_key.x) %>% unique() %>% pull())
length(l_not_included)
# 215

rep_char = rep(".", 15)

df_not_included = as.data.frame(t(c(l_not_included[1], rep_char)), stringsAsFactors=F)
colnames(df_not_included) = colnames(clinical_data_research_genomes)
for(i in 2:length(l_not_included)){
  df_not_included = rbind(df_not_included,
                          c(l_not_included[i], rep_char))
}


clinical_data_research_genomes = rbind(clinical_data_research_genomes,
                                       df_not_included)
dim(clinical_data_research_genomes)
# 89305  16

clinical_data_research_genomes %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 86457


# Let's write this with and without panel names

write.table(clinical_data_research_genomes, 
            file = "clinical_data_research_cohort_86457_genomes_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

clinical_data_research_genomes %>% filter(genome_build %in% "GRCh38") %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 58737 genomes
clinical_data_research_genomes %>% filter(genome_build %in% "GRCh38") %>% select(participant_id) %>% unique() %>% pull() %>% length()
# 58434 participants

write.table(clinical_data_research_genomes %>% filter(genome_build %in% "GRCh38"), 
            file = "clinical_data_research_cohort_86457_genomes_GRCh38_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

clinical_data_research_genomes %>% filter(!genome_build %in% "GRCh38") %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 29097
clinical_data_research_genomes %>% filter(!genome_build %in% "GRCh38") %>% select(participant_id) %>% unique() %>% pull() %>% length()
# 19041

write.table(clinical_data_research_genomes %>% filter(!genome_build %in% "GRCh38"), 
            file = "clinical_data_research_cohort_86457_genomes_GRCh37_and_NA_withPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)


# The same without panels

write.table(clinical_data_research_genomes[,-16], 
            file = "clinical_data_research_cohort_86457_genomes_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

clinical_data_research_genomes %>% filter(genome_build %in% "GRCh38") %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 58737
write.table(clinical_data_research_genomes[,-16] %>% filter(genome_build %in% "GRCh38"), 
            file = "clinical_data_research_cohort_86457_genomes_GRCh38_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)

clinical_data_research_genomes %>% filter(!genome_build %in% "GRCh38") %>% select(plate_key.x) %>% unique() %>% pull() %>% length()
# 29097
write.table(clinical_data_research_genomes[,-16] %>% filter(!genome_build %in% "GRCh38"), 
            file = "clinical_data_research_cohort_86457_genomes_GRCh37_and_NA_removingPanels_250919.tsv",
            quote = F,
            sep = "\t",
            row.names = F,
            col.names = T)
